# Author: Kiana Hosaka
# Date Last Modifiied: January 26, 2020	
# Description: Makefile to clean the output logs. `make clean`
clean:
	$(RM) term_log.tsv
	$(RM) daily_logs.tsv
	$(RM) testing_report.tsv
